### ISSUE TITLE
"Floating navigation at the bottom" cuts off video player at News section

### ISSUE THREAD

**Issue by justinsijbolts** [sakutaapp/sakuta-web#11]
![image](https://user-images.githubusercontent.com/39923540/163673229-f18b8d27-c846-4afd-a74a-e1d24be76071.png)

Floating navigation at the bottom cuts off video player at News section

**Comment by OfficialCRUGG** [comment]
Thanks for reporting! This is due to the footer being higher to make room for the floating navigation. This will be fixed in the next release!
