### ISSUE TITLE
Hover issue

### ISSUE THREAD

**Issue by justinsijbolts** [sakutaapp/sakuta-web#7]
Hovering right below the cover art completely removes the title. It's not in the cover art or below it when hovering there - except when you move your mouse away again
![issuehoversakuta](https://user-images.githubusercontent.com/39923540/162628471-75aae88b-c766-45a3-8178-cafe541dbf81.png)
.

**Comment by OfficialCRUGG** [comment]
Fix deployed in [52a2e37](https://github.com/sakutaapp/sakuta-web/commit/52a2e379b58a4c1016f29f880376e161aa5aa94a) now live on [Sakuta Dev](https://dev.sakuta.app).
Will be merged onto production in the next update.
