### ISSUE TITLE
Character limit for titles

### ISSUE THREAD

**Issue by justinsijbolts** [sakutaapp/sakuta-web#8]
Maybe make things like this (see attached image) max 2 rows - or add a character limit - and then just conclude it with "..." so that the spacing between rows isn't differen
![unknaown](https://user-images.githubusercontent.com/39923540/162628497-55e62002-e226-420a-8be9-32d559abacaf.png)
t

The same should be implemented on cover arts, as sometimes the title doesn't fit in the cover anymore :)

**Comment by OfficialCRUGG** [comment]
Fix deployed in [52a2e37](https://github.com/sakutaapp/sakuta-web/commit/52a2e379b58a4c1016f29f880376e161aa5aa94a) now live on [Sakuta Dev](https://dev.sakuta.app).
Will be merged onto production in the next update.
