### ISSUE TITLE
The scrollbar is the wrong colour

### ISSUE THREAD

**Issue by justinsijbolts** [sakutaapp/sakuta-web#9]
There's just a weird blue-ish coloured scroll bar when clicking CTRL + K

![wrongbar](https://user-images.githubusercontent.com/39923540/162628763-cd48cb3e-7797-4f08-ba6d-9eec7a950898.png)

**Comment by OfficialCRUGG** [comment]
![image](https://user-images.githubusercontent.com/25248999/162630596-2c9be7d3-d1a9-4d28-b533-c5e73a5bb221.png)
The scrollbar is also in the wrong color everywhere else. Will be fixed.

**Comment by OfficialCRUGG** [comment]
Fix deployed in [201a8b3](https://github.com/sakutaapp/sakuta-web/commit/201a8b312150d516643afc2bfd36cf0eebb31fc4) now live on [Sakuta Dev](https://dev.sakuta.app).
Will be merged onto production in the next update.
